"""Constants for the UltraWideLock Matter sensors integration."""

from homeassistant.const import Platform

DOMAIN = "uwb_matter"
CONF_CREDENTIAL_NAMES = "credential_names"
CONF_CREDENTIAL_PRESENCE = "credential_presence"
CONF_STALE_TIMEOUT = "stale_timeout_seconds"
CONF_WRITABLE_CONTROLS = "enable_writable_controls"
DEFAULT_STALE_TIMEOUT = 15
ENDPOINT_ID = 1
CUSTOM_CLUSTER_ID = 0xFFF1FC10
DOOR_LOCK_CLUSTER_ID = 0x0101
BINDING_CLUSTER_ID = 0x001E
BINDING_ATTRIBUTE_ID = 0x0000
DEVICE_IN_RANGE_ATTRIBUTE_ID = 0
DISTANCE_MM_ATTRIBUTE_ID = 1
CREDENTIAL_ID_ATTRIBUTE_ID = 2
UNLOCK_THRESHOLD_CM_ATTRIBUTE_ID = 3
MOVEMENT_STATE_ATTRIBUTE_ID = 4
LIVE_UWB_ATTRIBUTE_IDS = {
    DEVICE_IN_RANGE_ATTRIBUTE_ID,
    DISTANCE_MM_ATTRIBUTE_ID,
    CREDENTIAL_ID_ATTRIBUTE_ID,
    MOVEMENT_STATE_ATTRIBUTE_ID,
}
APPROACH_CM_ATTRIBUTE_ID = 5
RELOCK_CM_ATTRIBUTE_ID = 6
MOTOR_MS_ATTRIBUTE_ID = 7
DISTANCE_RELOCK_ATTRIBUTE_ID = 8
BOUND_UNLOCK_ATTRIBUTE_ID = 9
ULTRAWIDELOCK_RELOCK_ATTRIBUTE_ID = 10
ULTRAWIDELOCK_UNLOCK_ATTRIBUTE_ID = 11
LOCK_STATE_ATTRIBUTE_ID = 0x0000
LOCK_OPERATION_EVENT_ID = 0x0002
UNLOCK_OPERATION_TYPES = {1, 4}
ACTUATOR_ENABLED_ATTRIBUTE_ID = 0x0002
AUTO_RELOCK_TIME_ATTRIBUTE_ID = 0x0023
OPERATING_MODE_ATTRIBUTE_ID = 0x0025
PLATFORMS = [
    Platform.BINARY_SENSOR,
    Platform.EVENT,
    Platform.LOCK,
    Platform.NUMBER,
    Platform.SELECT,
    Platform.SENSOR,
    Platform.SWITCH,
]
